<a href="https://colab.research.google.com/github/abhishek9686/pythondata/blob/master/Tensorflow2_0_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
!pip install tensorflow==2.0.0-alpha0

     |████████████████████████████████| 79.9MB 73.7MB/s 
     |████████████████████████████████| 419kB 47.8MB/s 
     |████████████████████████████████| 3.0MB 31.7MB/s 
  Found existing installation: tensorflow 1.15.0
    Uninstalling tensorflow-1.15.0:
      Successfully uninstalled tensorflow-1.15.0


In [0]:
!pip install numpy

In [0]:
import tensorflow as tf
import numpy as np

In [11]:
print(tf.__version__)

2.0.0-alpha0


In [0]:
tensor_20=tf.constant([[1,2],[3,4]])

In [13]:
tensor_20

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [14]:
tensor_20.shape

TensorShape([2, 2])

In [15]:
tensor_20.numpy()

array([[1, 2],
       [3, 4]], dtype=int32)

In [0]:
numpy_tensor=np.array([[5,2],[3,4]])

In [0]:
tensor2=tf.constant(numpy_tensor)

In [22]:
tensor2+2

<tf.Tensor: id=8, shape=(2, 2), dtype=int64, numpy=
array([[7, 4],
       [5, 6]])>

In [23]:
tensor_20*2

<tf.Tensor: id=11, shape=(2, 2), dtype=int32, numpy=
array([[2, 4],
       [6, 8]], dtype=int32)>

In [25]:
np.square(tensor2)

array([[25,  4],
       [ 9, 16]])

In [26]:
np.dot(tensor_20,tensor2)

array([[11, 10],
       [27, 22]])